TelerikDemo/Controllers/TelerikAjaxGridController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
// this based on some code that telerik made openesource see below
// a third party made the Nuget Package Kendo.DynamicLinqCore - note the default one didnt work!
// https://www.telerik.com/blogs/kendo-ui-open-sources-dynamic-linq-helpers
// https://github.com/kendo-labs/dlinq-helpers // kendo made this
// https://github.com/linmasaki/Kendo.DynamicLinqCore // someone else made this - I suppose from the above code
using Kendo.DynamicLinqCore;
using Microsoft.AspNetCore.Mvc;
using TelerikDemo.Models;

namespace TelerikDemo.Controllers
{
    public class TelerikAjaxGridController : Controller
    {

        private readonly TelerikDemoContext _telerikDemoContext;
        public TelerikAjaxGridController(TelerikDemoContext telerikDemoContext)
        {
            _telerikDemoContext = telerikDemoContext;
        }

         public IActionResult Index()
        {
            return View();
        }

        // DataSourceRequest is defined in the Kendo.DynamicLinqCore - it matches the model that kendo grid uses for filtering/paging and sorting on the server
        [HttpPost]
        public JsonResult Read([FromBody]DataSourceRequest r)
        {
            var allcars = _telerikDemoContext.Cars;

            // ToDataSourceResult is an extension that Kendo.DynamicLinqCore defines to dynamically apply server paging/filters and sorting all together
            var dm = allcars.Select(s=> new CarViewModel
            {
                Id = s.Id,
                Make = s.Make,
                AirConditioner = s.AirConditioner,
                CarType = s.CarType,
                Model = s.Model,
                Year = s.Year,
                DateModified = s.DateModified
            }).ToDataSourceResult(r.Take, r.Skip, r.Sort, r.Filter);

            // when the Json gets sent back asp.net core converts the properties to camelCase standard Json. 
            return new JsonResult(dm); 
        }

        [HttpPost]
        public JsonResult Create([FromBody]IEnumerable<CarViewModel> cars)
        {
            // we need to project the vm that is bound in the request to 
            // a set of Car model objects to insert into the database
            // this could be done using AutoMapper or similarto simplify
            var carsmodels = cars.Select(s => new Car
            {
                // id is null so dont include
                Make = s.Make,
                AirConditioner = s.AirConditioner,
                CarType = s.CarType,
                Model = s.Model,
                Year = s.Year,
                DateModified = s.DateModified
            });
            _telerikDemoContext.Cars.AddRange(carsmodels);
            _telerikDemoContext.SaveChanges();

            // For consistency project back to a view model
            // the kendo grid needs to be updated with the Ids of the freshly inserted Entities
            var carsvm = carsmodels.Select(s => new CarViewModel
            {
                Id = s.Id,
                Make = s.Make,
                AirConditioner = s.AirConditioner,
                CarType = s.CarType,
                Model = s.Model,
                Year = s.Year,
                DateModified = s.DateModified
            });
            return new JsonResult(carsvm);
        }

        [HttpPost]
        public JsonResult Update([FromBody]IEnumerable<CarViewModel> cars)
        {
            // for updating the UpdateRange EF core function will update matching entities as long as the Id is available and matches. The kendo grid shouldnt sent id null when it updates
            var carsmodels = cars.Select(s => new Car
            {
                Id = s.Id??0,
                Make = s.Make,
                AirConditioner = s.AirConditioner,
                CarType = s.CarType,
                Model = s.Model,
                Year = s.Year,
                DateModified = s.DateModified
            });

            _telerikDemoContext.UpdateRange(carsmodels);
            _telerikDemoContext.SaveChanges();

            return new JsonResult(cars);
        }

        [HttpPost]
        public JsonResult Destroy([FromBody]IEnumerable<CarViewModel> cars)
        {
            // for updating the RemoveRange EF core function will remove matching entities as long as the Id is available and matches. The kendo grid shouldnt sentd id null when it deletes an existing row!

            var carsmodels = cars.Select(s => new Car
            {
                Id = s.Id ?? 0,
                Make = s.Make,
                AirConditioner = s.AirConditioner,
                CarType = s.CarType,
                Model = s.Model,
                Year = s.Year,
                DateModified = s.DateModified
            });


            _telerikDemoContext.Cars.RemoveRange(carsmodels);
            _telerikDemoContext.SaveChanges();

            return new JsonResult(cars);
        }
    }
}

TelerikDemo/Controllers/TelerikStaticGridController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TelerikDemo.Models;

namespace TelerikDemo.Controllers
{
    public class TelerikStaticGridController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TelerikDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Telerik Demo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>

    @* Standard telerik css files *@
    @*<link href="~/css/kendo.common.min.css" rel="stylesheet" />
        <link href="~/css/kendo.default.min.css" rel="stylesheet" />
        <link href="~/css/kendo.default.mobile.min.css" rel="stylesheet" />*@

    @* Bootstrap v3 telerik css files *@
    @*<link href="https://kendo.cdn.telerik.com/2019.2.619/styles/kendo.common-bootstrap.min.css" rel="stylesheet" />
    <link href="https://kendo.cdn.telerik.com/2019.2.619/styles/kendo.rtl.min.css" rel="stylesheet" />
    <link href="https://kendo.cdn.telerik.com/2019.2.619/styles/kendo.bootstrap.min.css" rel="stylesheet" />
    <link href="https://kendo.cdn.telerik.com/2019.2.619/styles/kendo.bootstrap.mobile.min.css" rel="stylesheet" />*@

    @* Bootstrap v4 telerik css files (cdn and local) *@
    <link href="~/css/kendo.bootstrap-v4.min.css" rel="stylesheet" />
    @*<link href="https://kendo.cdn.telerik.com/2019.2.619/styles/kendo.bootstrap-v4.min.css" rel="stylesheet" />*@

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                @*<a class="navbar-brand"  asp-area=""  asp-page="TelerikAjaxGridRazor">Ajax Grid (Razor)</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TelerikAjaxGrid" asp-action="Index">Ajax Grid</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TelerikStaticGrid" asp-action="Index">Table Grid</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Telerik Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

        @* 
            Minimal kendo using a custom build file see: https://www.telerik.com/download/custom-download
        *@
        <script src="~/js/kendo.custom.min.js"></script> 
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script type="text/javascript">
        //set current to the "en-GB" culture script
        kendo.culture("en-GB");
    </script>

    @RenderSection("Scripts", required: false)

</body>


</html>